version: "2"
services:
  face_rec_redis:
    restart: always
    image: redis:4-alpine
    volumes:
      - "./redis.conf:/etc/redis/redis.conf"
      - "./data:/data"
    ports:
      - "6379:6379/tcp"
    command:
       redis-server /etc/redis/redis.conf --appendonly yes

