# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "zh_CN.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20180126.0.0"
  config.vm.hostname = "Ubuntu-with-docker"
  config.vm.provision "shell", path: "init.sh", run: "once"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 9000, host: 9000
end
